# Generated by Django 4.1.3 on 2022-11-15 14:05

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagiario',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=11),
        ),
    ]
