# Generated by Django 4.1.3 on 2022-11-15 15:11

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_alter_estagiario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagiario',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=11, unique=True),
        ),
    ]
