# Generated by Django 4.1.3 on 2022-11-16 03:49

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_alter_estagiario_setoralocado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagiario',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, unique=True),
        ),
    ]
