# Generated by Django 4.1.3 on 2022-11-16 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_alter_estagiario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagiario',
            name='setorAlocado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setor', to='restapi.setor'),
        ),
    ]
